# generated by datamodel-codegen:
#   filename:  index.yaml
#   timestamp: 2025-06-10T01:59:36+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class ContentType(Enum):
    hymn = 'hymn'
    liturgy = 'liturgy'
    bible = 'bible'


class Hymn(BaseModel):
    id: UUID
    name: str
    author: Optional[str] = None
    composer: Optional[str] = None


class Liturgy(BaseModel):
    id: UUID
    name: str


class LiturgyBlock(BaseModel):
    id: UUID
    liturgy_id: str
    name: Optional[str] = None
    position: Optional[int] = None


class Bible(BaseModel):
    id: UUID
    reference: str
    translation: Optional[str] = None


class Pack(BaseModel):
    id: UUID
    name: str
    author: Optional[str] = None
    description: Optional[str] = None
    created_at: Optional[date] = None


class PackItem(BaseModel):
    pack_id: UUID
    content_id: UUID


class Slide(BaseModel):
    id: UUID
    content_id: UUID
    position: Optional[int] = None


class SlideColumn(BaseModel):
    id: UUID
    slide_id: UUID
    position: Optional[int] = None
    content: Optional[str] = None
    header: Optional[str] = None


class Tag(BaseModel):
    id: UUID
    name: str


class TagAssignment(BaseModel):
    tag_id: UUID
    content_id: UUID
    content_type: ContentType


class SlideColumnView(BaseModel):
    id: str
    position: int
    header: str
    content: str


class PackItemView(BaseModel):
    id: str
    type: ContentType


class Content(BaseModel):
    id: UUID = Field(..., description='Unique identifier for the content item.')
    type: ContentType
    created_at: Optional[date] = Field(
        None, description='timestamp when the content was created.'
    )


class Tables(BaseModel):
    contents: Optional[List[Content]] = None
    hymns: Optional[List[Hymn]] = None
    liturgies: Optional[List[Liturgy]] = None
    liturgies_blocks: Optional[List[LiturgyBlock]] = None
    bible: Optional[List[Bible]] = None
    packs: Optional[List[Pack]] = None
    packs_items: Optional[List[PackItem]] = None
    slides: Optional[List[Slide]] = None
    slide_columns: Optional[List[SlideColumn]] = None
    tags: Optional[List[Tag]] = None


class SlideView(BaseModel):
    slide_id: str
    position: int
    columns: Optional[List[SlideColumnView]] = None


class PackView(BaseModel):
    id: Optional[UUID] = None
    name: Optional[str] = None
    author: Optional[str] = None
    description: Optional[str] = None
    created_at: Optional[date] = None
    items: Optional[List[PackItemView]] = None


class HymnView(BaseModel):
    id: UUID
    name: str
    author: Optional[str] = None
    composer: Optional[str] = None
    created_at: Optional[date] = None
    tags: Optional[List[str]] = None
    slides: Optional[List[SlideView]] = None
