# generated by datamodel-codegen:
#   filename:  index.yaml
#   timestamp: 2026-06-04T23:49:36+00:00

from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from uuid import UUID

from pydantic import BaseModel, Extra, Field


class ContentType(str, Enum):
    hymn = 'hymn'
    book = 'book'
    book_chapter = 'book_chapter'
    book_section = 'book_section'
    bible = 'bible'
    bible_book = 'bible_book'
    bible_chapter = 'bible_chapter'


class Hymn(BaseModel):
    id: UUID
    name: str
    author: str | None = None
    composer: str | None = None


class Language(BaseModel):
    id: UUID
    language_code: str
    variant: str | None = None
    name: str
    is_rtl: bool | None = False


class Book(BaseModel):
    id: UUID
    name: str = Field(
        ...,
        description='Name of this book (can be multilingual if book contains multiple languages)',
    )
    author: str | None = None
    description: str | None = None
    isbn: str | None = Field(
        None, description='Optional ISBN identifier for published books'
    )
    created_by: str | None = None
    created_at: datetime | None = None


class BookChapter(BaseModel):
    id: UUID
    name: str = Field(..., description='Name of this chapter')
    description: str | None = None
    created_by: str | None = None
    created_at: datetime | None = None


class BookChapterLink(BaseModel):
    book_id: UUID
    chapter_id: UUID
    position: int


class BookSection(BaseModel):
    id: UUID
    chapter_id: UUID
    position: int
    name: str = Field(
        ..., description='Name of this section (language inherited from parent chapter)'
    )
    description: str | None = None
    rubric: str | None = Field(None, description='Liturgical instructions or notes')
    created_by: str | None = None


class Bible(BaseModel):
    id: UUID
    translation_id: str


class BibleBook(BaseModel):
    id: UUID
    bible_id: UUID
    canon_order: int
    name_id: str | None = None
    name_lang: str
    name_lang_abbr: str | None = None


class BibleChapter(BaseModel):
    id: UUID
    bible_book_id: UUID
    number: int


class BibleTranslation(BaseModel):
    id: str
    abbr: str
    name: str
    is_default: bool | None = False


class Pack(BaseModel):
    id: UUID
    name: str
    author: str | None = None
    description: str | None = None
    created_at: date | None = None


class PackItem(BaseModel):
    pack_id: UUID
    content_id: UUID


class Slide(BaseModel):
    id: UUID
    content_id: UUID
    position: int | None = None


class SlideRow(BaseModel):
    id: UUID
    slide_id: UUID
    position: int
    columns: int = Field(..., description='Number of columns in this row')


class SlideColumn(BaseModel):
    id: UUID
    row_id: UUID
    position: int
    language_id: UUID = Field(
        ...,
        description='Reference to the language for this column (affects text direction)',
    )


class BlockType(str, Enum):
    h1 = 'h1'
    h2 = 'h2'
    h3 = 'h3'
    paragraph = 'paragraph'


class BlockAlign(str, Enum):
    center_ = 'center'
    left = 'left'
    right = 'right'


class Tag(BaseModel):
    id: UUID
    name: str


class TagAssignment(BaseModel):
    tag_id: UUID
    content_id: UUID
    content_type: ContentType


class BibleView(BaseModel):
    id: UUID
    type: ContentType
    created_at: str
    translation: BibleTranslation
    books_count: int
    chapters_count: int


class Bible2(BaseModel):
    id: UUID
    translation: BibleTranslation


class Chapter(BaseModel):
    id: str
    number: int


class BibleBookView(BaseModel):
    id: UUID
    type: ContentType
    created_at: str
    canon_order: int
    name_id: str
    name_lang: str
    name_lang_abbr: str | None = None
    bible: Bible2
    chapters_count: int
    chapters: list[Chapter]


class Book2(BaseModel):
    id: UUID
    name_id: str
    name_lang: str
    name_lang_abbr: str


class PaginationInfo(BaseModel):
    current_page: int | None = None
    page_size: int | None = None
    total_items: int | None = None
    total_pages: int | None = None
    min_page: int | None = None
    max_page: int | None = None
    has_next: bool | None = None
    has_previous: bool | None = None
    next_page: int | None = None
    previous_page: int | None = None
    first_page: int | None = None
    last_page: int | None = None
    items_on_current_page: int | None = None
    offset: int | None = None
    is_first_page: bool | None = None
    is_last_page: bool | None = None


class BibleChaptersPagedView(BaseModel):
    items: list[BibleChapter]
    pagination: PaginationInfo
    book_data: BibleBook
    translation_data: BibleTranslation


class Section(BaseModel):
    section_id: UUID
    position: int
    name: str
    description: str | None = None
    rubric: str | None = None
    created_by: str | None = None
    slide_count: int = Field(..., description='Number of slides in this section')


class Chapter1(BaseModel):
    chapter_id: UUID
    position: int
    name: str
    description: str | None = None
    created_by: str | None = None
    sections: list[Section]


class BookView(BaseModel):
    book_id: UUID
    name: str
    author: str | None = None
    description: str | None = None
    isbn: str | None = None
    created_by: str | None = None
    chapters: list[Chapter1]


class Content(BaseModel):
    id: UUID = Field(..., description='Unique identifier for the content item.')
    type: ContentType
    created_at: date | None = Field(
        None, description='timestamp when the content was created.'
    )


class BlockStyle(BaseModel):
    class Config:
        extra = Extra.allow

    type: BlockType = Field(
        ..., description='Semantic block type (h1, h2, h3, paragraph)'
    )
    align: BlockAlign | None = Field(
        None, description='Text alignment hint (e.g. left, center, right)'
    )


class SlideBlockView(BaseModel):
    id: str
    position: int
    content: str
    metadata: BlockStyle


class BibleBooksPagedView(BaseModel):
    items: list[BibleBook]
    pagination: PaginationInfo
    bible_data: Bible
    translation_data: BibleTranslation


class SlideBlock(BaseModel):
    id: UUID
    column_id: UUID = Field(..., description='Reference to the parent slide column')
    content_type: ContentType = Field(
        ..., description='Denormalized content type for search optimization'
    )
    position: int = Field(..., description='Order of this block within the column')
    content: str = Field(..., description='The actual text content of the block')
    metadata: BlockStyle = Field(
        ...,
        description='Block styling (semantic type, alignment, etc.) stored as JSONB',
    )


class Tables(BaseModel):
    content: list[Content] | None = None
    hymn: list[Hymn] | None = None
    language: list[Language] | None = None
    book: list[Book] | None = None
    book_chapter: list[BookChapter] | None = None
    book_chapter_link: list[BookChapterLink] | None = None
    book_section: list[BookSection] | None = None
    bible: list[Bible] | None = None
    bible_book: list[BibleBook] | None = None
    bible_chapter: list[BibleChapter] | None = None
    bible_translation: list[BibleTranslation] | None = None
    pack: list[Pack] | None = None
    pack_item: list[PackItem] | None = None
    slide: list[Slide] | None = None
    slide_row: list[SlideRow] | None = None
    slide_column: list[SlideColumn] | None = None
    slide_block: list[SlideBlock] | None = None
    tag: list[Tag] | None = None


class SlideColumnView(BaseModel):
    id: str
    position: int
    language: Language = Field(..., description='Language details for this column')
    blocks: list[SlideBlockView]


class SlideRowView(BaseModel):
    id: str
    position: int
    columns: int
    slide_columns: list[SlideColumnView]


class SlideView(BaseModel):
    slide_id: str
    position: int
    slide_rows: list[SlideRowView]


class ContentSlidesView(BaseModel):
    content_id: UUID | None = None
    content_type: ContentType
    slides: list[SlideView]


class HymnView(BaseModel):
    id: UUID
    name: str
    author: str | None = None
    composer: str | None = None
    created_at: date | None = None
    tags: list[str] | None = None
    slides: list[SlideView] | None = None


class BookSectionView(BaseModel):
    section_id: UUID
    position: int
    name: str
    description: str | None = None
    rubric: str | None = None
    created_by: str | None = None
    slides: list[SlideView]


class PackItemView(BaseModel):
    id: str
    type: ContentType
    create_at: date | None = None
    content: HymnView | BookView | BibleView | None = None


class BibleChapterView(BaseModel):
    id: UUID
    type: ContentType
    created_at: str
    number: int
    book: Book2
    bible: Bible2
    slides: list[SlideView]
    display_name: str
    short_display_name: str


class PackView(BaseModel):
    id: UUID | None = None
    name: str | None = None
    author: str | None = None
    description: str | None = None
    created_at: date | None = None
    pagination: PaginationInfo | None = None
    items: list[PackItemView] | None = None
