# generated by datamodel-codegen:
#   filename:  index.yaml
#   timestamp: 2025-08-12T08:35:59+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import List, Optional, Union
from uuid import UUID

from pydantic import BaseModel, Field


class ContentType(str, Enum):
    hymn = 'hymn'
    liturgy = 'liturgy'
    liturgy_block = 'liturgy_block'
    bible = 'bible'
    bible_book = 'bible_book'
    bible_chapter = 'bible_chapter'


class Hymn(BaseModel):
    id: UUID
    name: str
    author: Optional[str] = None
    composer: Optional[str] = None


class Liturgy(BaseModel):
    id: UUID
    name: str


class LiturgyBlock(BaseModel):
    id: UUID
    liturgy_id: str
    name: Optional[str] = None
    position: Optional[int] = None


class Bible(BaseModel):
    id: UUID
    translation_id: str


class BibleBook(BaseModel):
    id: UUID
    bible_id: UUID
    canon_order: int
    name_id: Optional[str] = None
    name_lang: str
    name_lang_abbr: Optional[str] = None


class BibleChapter(BaseModel):
    id: UUID
    bible_book_id: UUID
    number: int


class BibleTranslation(BaseModel):
    id: str
    abbr: str
    name: str


class Pack(BaseModel):
    id: UUID
    name: str
    author: Optional[str] = None
    description: Optional[str] = None
    created_at: Optional[date] = None


class PackItem(BaseModel):
    pack_id: UUID
    content_id: UUID


class Slide(BaseModel):
    id: UUID
    content_id: UUID
    position: Optional[int] = None


class SlideColumn(BaseModel):
    id: UUID
    slide_id: UUID
    content_type: ContentType
    position: Optional[int] = None
    content: Optional[str] = None
    header: Optional[str] = None


class Tag(BaseModel):
    id: UUID
    name: str


class TagAssignment(BaseModel):
    tag_id: UUID
    content_id: UUID
    content_type: ContentType


class BibleView(BaseModel):
    id: UUID
    type: ContentType
    created_at: str
    translation: BibleTranslation
    books_count: int
    chapters_count: int


class Bible2(BaseModel):
    id: Optional[UUID] = None
    translation: Optional[BibleTranslation] = None


class Chapter(BaseModel):
    id: Optional[str] = None
    number: Optional[int] = None


class BibleBookView(BaseModel):
    id: UUID
    type: ContentType
    created_at: str
    canon_order: int
    name_id: str
    name_lang: str
    name_lang_abbr: Optional[str] = None
    bible: Bible2
    chapters_count: int
    chapters: List[Chapter]


class Book(BaseModel):
    id: Optional[UUID] = None
    name_id: Optional[str] = None
    name_lang: Optional[str] = None
    name_lang_abbr: Optional[str] = None


class SlideColumnView(BaseModel):
    id: str
    position: int
    content_type: ContentType
    header: str
    content: str


class PaginationInfo(BaseModel):
    current_page: Optional[int] = None
    page_size: Optional[int] = None
    total_items: Optional[int] = None
    total_pages: Optional[int] = None
    min_page: Optional[int] = None
    max_page: Optional[int] = None
    has_next: Optional[bool] = None
    has_previous: Optional[bool] = None
    next_page: Optional[int] = None
    previous_page: Optional[int] = None
    first_page: Optional[int] = None
    last_page: Optional[int] = None
    items_on_current_page: Optional[int] = None
    offset: Optional[int] = None
    is_first_page: Optional[bool] = None
    is_last_page: Optional[bool] = None


class BibleChaptersPagedView(BaseModel):
    items: List[BibleChapter]
    pagination: PaginationInfo
    book_data: BibleBook
    translation_data: BibleTranslation


class Content(BaseModel):
    id: UUID = Field(..., description='Unique identifier for the content item.')
    type: ContentType
    created_at: Optional[date] = Field(
        None, description='timestamp when the content was created.'
    )


class Tables(BaseModel):
    content: Optional[List[Content]] = None
    hymn: Optional[List[Hymn]] = None
    liturgy: Optional[List[Liturgy]] = None
    liturgy_block: Optional[List[LiturgyBlock]] = None
    bible: Optional[List[Bible]] = None
    bible_book: Optional[List[BibleBook]] = None
    bible_chapter: Optional[List[BibleChapter]] = None
    bible_translation: Optional[List[BibleTranslation]] = None
    pack: Optional[List[Pack]] = None
    pack_item: Optional[List[PackItem]] = None
    slide: Optional[List[Slide]] = None
    slide_column: Optional[List[SlideColumn]] = None
    tag: Optional[List[Tag]] = None


class SlideView(BaseModel):
    slide_id: str
    position: int
    columns: Optional[List[SlideColumnView]] = None


class BibleBooksPagedView(BaseModel):
    items: List[BibleBook]
    pagination: PaginationInfo
    bible_data: Bible
    translation_data: BibleTranslation


class ContentSlidesView(BaseModel):
    content_id: Optional[UUID] = None
    content_type: ContentType
    slides: List[SlideView]


class HymnView(BaseModel):
    id: UUID
    name: str
    author: Optional[str] = None
    composer: Optional[str] = None
    created_at: Optional[date] = None
    tags: Optional[List[str]] = None
    slides: Optional[List[SlideView]] = None


class BlockView(BaseModel):
    block_id: UUID
    name: str
    position: int
    slides: Optional[List[SlideView]] = None


class BibleChapterView(BaseModel):
    id: UUID
    type: ContentType
    created_at: str
    number: int
    book: Book
    bible: Bible2
    slides: List[SlideView]
    display_name: str
    short_display_name: str


class LiturgyView(BaseModel):
    liturgy_id: UUID
    liturgy_name: str
    blocks: Optional[List[BlockView]] = None


class PackItemView(BaseModel):
    id: str
    type: ContentType
    create_at: Optional[date] = None
    content: Optional[Union[HymnView, LiturgyView, BibleView]] = None


class PackView(BaseModel):
    id: Optional[UUID] = None
    name: Optional[str] = None
    author: Optional[str] = None
    description: Optional[str] = None
    created_at: Optional[date] = None
    pagination: Optional[PaginationInfo] = None
    items: Optional[List[PackItemView]] = None
