openapi: 3.0.0
paths: {}
info:
  title: Hymnos Models API
  version: 1.0.0
components:
  schemas:
    Content:
      $ref: "./components/schemas/Content.yaml"
    Hymn:
      $ref: "./components/schemas/Hymn.yaml"
    Liturgy:
      $ref: "./components/schemas/Liturgy.yaml"
    LiturgyBlock:
      $ref: "./components/schemas/LiturgyBlock.yaml"
    Bible:
      $ref: "./components/schemas/Bible.yaml"
    BibleBook:
      $ref: "./components/schemas/BibleBook.yaml"
    BibleChapter:
      $ref: "./components/schemas/BibleChapter.yaml"
    BibleTranslation:
      $ref: "./components/schemas/BibleTranslation.yaml"
    Pack:
      $ref: "./components/schemas/Pack.yaml"
    PackItem:
      $ref: "./components/schemas/PackItem.yaml"
    Slide:
      $ref: "./components/schemas/Slide.yaml"
    SlideColumn:
      $ref: "./components/schemas/SlideColumn.yaml"
    Tag:
      $ref: "./components/schemas/Tag.yaml"
    TagAssignment:
      $ref: "./components/schemas/TagAssignment.yaml"
    Tables:
      $ref: "./components/schemas/Tables.yaml"
    BibleView:
      $ref: "./components/schemas/Views/BibleView.yaml"
    BibleBookView:
      $ref: "./components/schemas/Views/BibleBookView.yaml"
    BibleChapterView:
      $ref: "./components/schemas/Views/BibleChapterView.yaml"
    BibleBooksPagedView:
      $ref: "./components/schemas/Views/BibleBooksPagedView.yaml"
    BibleChaptersPagedView:
      $ref: "./components/schemas/Views/BibleChaptersPagedView.yaml"
    ContentSlidesView:
      $ref: "./components/schemas/Views/ContentSlidesView.yaml"
    HymnView:
      $ref: "./components/schemas/Views/HymnView.yaml"
    PackView:
      $ref: "./components/schemas/Views/PackView.yaml"
