/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** @description Supertype for all content items like hymns, liturgies, and bible readings. */
        Content: {
            /**
             * Format: uuid
             * @description Unique identifier for the content item.
             */
            id: string;
            type: components["schemas"]["ContentType"];
            /**
             * Format: date
             * @description timestamp when the content was created.
             */
            created_at?: string;
        };
        /** @description A musical piece used in worship. */
        Hymn: {
            /** Format: uuid */
            id: string;
            name: string;
            author?: string;
            composer?: string;
        };
        Language: {
            /** Format: uuid */
            id: string;
            language_code: string;
            variant?: string;
            name: string;
            /** @default false */
            is_rtl: boolean;
        };
        Book: {
            /** Format: uuid */
            id: string;
            /** @description Name of this book (can be multilingual if book contains multiple languages) */
            name: string;
            author?: string;
            description?: string;
            /** @description Optional ISBN identifier for published books */
            isbn?: string;
            created_by?: string;
            /** Format: date-time */
            created_at?: string;
        };
        /** @description A single node in a book's hierarchy tree. Self-references via parent_id to allow arbitrary nesting depth (chapter -> section -> sub-section -> ...). Slides may attach to any node via slide.content_id. book_id is denormalized for direct ownership lookup. */
        BookNode: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            book_id: string;
            /**
             * Format: uuid
             * @description Parent node id, or null for a top-level node directly under the book
             */
            parent_id?: string;
            position: number;
            /** @description Name of this node */
            name: string;
            description?: string;
            created_by?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Bible: {
            /** Format: uuid */
            id: string;
            translation_id: string;
        };
        BibleBook: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            bible_id: string;
            canon_order: number;
            name_id?: string;
            name_lang: string;
            name_lang_abbr?: string;
        };
        BibleChapter: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            bible_book_id: string;
            number: number;
        };
        BibleTranslation: {
            id: string;
            abbr: string;
            name: string;
            /** @default false */
            is_default: boolean;
        };
        /** @description A collection of content items grouped together. */
        Pack: {
            /** Format: uuid */
            id: string;
            name: string;
            author?: string;
            description?: string;
            /** Format: date */
            created_at?: string;
        };
        PackItem: {
            /** Format: uuid */
            pack_id: string;
            /** Format: uuid */
            content_id: string;
        };
        Slide: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            content_id: string;
            position?: number;
        };
        /** @description A horizontal row within a slide that can contain multiple columns */
        SlideRow: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            slide_id: string;
            position: number;
            /**
             * @description Number of columns in this row
             * @default 1
             */
            columns: number;
        };
        /** @description A column within a slide row that contains one or more content blocks */
        SlideColumn: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            row_id: string;
            position: number;
            /**
             * Format: uuid
             * @description Reference to the language for this column (affects text direction)
             */
            language_id: string;
        };
        /** @description A content block within a slide column (e.g., heading, paragraph) */
        SlideBlock: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Reference to the parent slide column
             */
            column_id: string;
            /** @description Denormalized content type for search optimization */
            content_type: components["schemas"]["ContentType"];
            /** @description Order of this block within the column */
            position: number;
            /** @description The actual text content of the block */
            content: string;
            /** @description Block styling (semantic type, alignment, etc.) stored as JSONB */
            metadata: components["schemas"]["BlockStyle"];
        };
        /**
         * @description Type of content block within a slide column
         * @enum {string}
         */
        BlockType: BlockType;
        /**
         * @description Type of content block within a slide column
         * @enum {string}
         */
        BlockAlign: BlockAlign;
        /** @description Styling for a slide block, stored as JSONB. Holds the block's semantic type and presentation hints. Extensible: additional fields may be added over time without a schema migration. */
        BlockStyle: {
            /** @description Semantic block type (h1, h2, h3, paragraph) */
            type: components["schemas"]["BlockType"];
            /** @description Text alignment hint (e.g. left, center, right) */
            align?: components["schemas"]["BlockAlign"];
        } & {
            [key: string]: unknown;
        };
        /** @enum {string} */
        ContentType: ContentType;
        Tag: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        TagAssignment: {
            /** Format: uuid */
            tag_id: string;
            /** Format: uuid */
            content_id: string;
            content_type: components["schemas"]["ContentType"];
        };
        Tables: {
            content?: components["schemas"]["Content"][];
            hymn?: components["schemas"]["Hymn"][];
            language?: components["schemas"]["Language"][];
            book?: components["schemas"]["Book"][];
            book_node?: components["schemas"]["BookNode"][];
            bible?: components["schemas"]["Bible"][];
            bible_book?: components["schemas"]["BibleBook"][];
            bible_chapter?: components["schemas"]["BibleChapter"][];
            bible_translation?: components["schemas"]["BibleTranslation"][];
            pack?: components["schemas"]["Pack"][];
            pack_item?: components["schemas"]["PackItem"][];
            slide?: components["schemas"]["Slide"][];
            slide_row?: components["schemas"]["SlideRow"][];
            slide_column?: components["schemas"]["SlideColumn"][];
            slide_block?: components["schemas"]["SlideBlock"][];
            tag?: components["schemas"]["Tag"][];
        };
        BibleView: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["ContentType"];
            created_at: string;
            translation: components["schemas"]["BibleTranslation"];
            books_count: number;
            chapters_count: number;
        };
        BibleBookView: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["ContentType"];
            created_at: string;
            canon_order: number;
            name_id: string;
            name_lang: string;
            name_lang_abbr?: string;
            bible: {
                /** Format: uuid */
                id: string;
                translation: components["schemas"]["BibleTranslation"];
            };
            chapters_count: number;
            chapters: {
                id: string;
                number: number;
            }[];
        };
        BibleChapterView: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["ContentType"];
            created_at: string;
            number: number;
            book: {
                /** Format: uuid */
                id: string;
                name_id: string;
                name_lang: string;
                name_lang_abbr: string;
            };
            bible: {
                /** Format: uuid */
                id: string;
                translation: components["schemas"]["BibleTranslation"];
            };
            slides: components["schemas"]["SlideView"][];
            display_name: string;
            short_display_name: string;
        };
        BibleBooksPagedView: {
            items: components["schemas"]["BibleBook"][];
            pagination: components["schemas"]["PaginationInfo"];
            bible_data: components["schemas"]["Bible"];
            translation_data: components["schemas"]["BibleTranslation"];
        };
        BibleChaptersPagedView: {
            items: components["schemas"]["BibleChapter"][];
            pagination: components["schemas"]["PaginationInfo"];
            book_data: components["schemas"]["BibleBook"];
            translation_data: components["schemas"]["BibleTranslation"];
        };
        ContentSlidesView: {
            /** Format: uuid */
            content_id?: string;
            content_type: components["schemas"]["ContentType"];
            slides: components["schemas"]["SlideView"][];
        };
        /** @description A database view for ease of use on frontend side */
        HymnView: {
            /** Format: uuid */
            id: string;
            name: string;
            author?: string;
            composer?: string;
            /** Format: date */
            created_at?: string;
            tags?: string[];
            slides?: components["schemas"]["SlideView"][];
        };
        /** @description Book structure view - metadata plus a FLAT list of nodes in pre-order (depth-first) traversal order. Assemble the tree client-side via parent_id; the order also doubles as the presentation reading order. Slide content is fetched separately per node. */
        BookView: {
            /** Format: uuid */
            book_id: string;
            name: string;
            author?: string;
            description?: string;
            isbn?: string;
            created_by?: string;
            nodes: {
                /** Format: uuid */
                node_id: string;
                /**
                 * Format: uuid
                 * @description Parent node id, or null for a top-level node
                 */
                parent_id?: string | null;
                position: number;
                /** @description 1 for top-level nodes, incrementing with nesting */
                depth: number;
                name: string;
                description?: string;
                created_by?: string;
                /** @description Number of slides attached directly to this node */
                slide_count: number;
            }[];
        };
        /** @description A pack containing multiple items. */
        PackView: {
            /** Format: uuid */
            id?: string;
            name?: string;
            author?: string;
            description?: string;
            /** Format: date */
            created_at?: string;
            pagination?: components["schemas"]["PaginationInfo"];
            items?: components["schemas"]["PackItemView"][];
        };
        /** @description A complete slide with all its rows */
        SlideView: {
            slide_id: string;
            position: number;
            slide_rows: components["schemas"]["SlideRowView"][];
        };
        /** @description A row in a slide with its columns */
        SlideRowView: {
            id: string;
            position: number;
            columns: number;
            slide_columns: components["schemas"]["SlideColumnView"][];
        };
        /** @description A column in a slide row containing content blocks */
        SlideColumnView: {
            id: string;
            position: number;
            /** @description Language details for this column */
            language: components["schemas"]["Language"];
            blocks: components["schemas"]["SlideBlockView"][];
        };
        /** @description A content block within a slide column */
        SlideBlockView: {
            id: string;
            position: number;
            content: string;
            metadata: components["schemas"]["BlockStyle"];
        };
        PaginationInfo: {
            current_page?: number;
            page_size?: number;
            total_items?: number;
            total_pages?: number;
            min_page?: number;
            max_page?: number;
            has_next?: boolean;
            has_previous?: boolean;
            next_page?: number;
            previous_page?: number;
            first_page?: number;
            last_page?: number;
            items_on_current_page?: number;
            offset?: number;
            is_first_page?: boolean;
            is_last_page?: boolean;
        };
        /** @description A pack item showing its type (hymn, bible, liturgy) and id only */
        PackItemView: {
            id: string;
            type: components["schemas"]["ContentType"];
            /** Format: date */
            create_at?: string;
            content?: components["schemas"]["HymnView"] | components["schemas"]["BookView"] | components["schemas"]["BibleView"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export enum BlockType {
    h1 = "h1",
    h2 = "h2",
    h3 = "h3",
    paragraph = "paragraph"
}
export enum BlockAlign {
    center = "center",
    left = "left",
    right = "right"
}
export enum ContentType {
    hymn = "hymn",
    book = "book",
    book_node = "book_node",
    bible = "bible",
    bible_book = "bible_book",
    bible_chapter = "bible_chapter"
}
export type operations = Record<string, never>;
