/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** @description Supertype for all content items like hymns, liturgies, and bible readings. */
        Content: {
            /**
             * Format: uuid
             * @description Unique identifier for the content item.
             */
            id: string;
            type: components["schemas"]["ContentType"];
            /**
             * Format: date
             * @description timestamp when the content was created.
             */
            created_at?: string;
        };
        /** @description A musical piece used in worship. */
        Hymn: {
            /** Format: uuid */
            id: string;
            name: string;
            author?: string;
            composer?: string;
        };
        Liturgy: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        LiturgyBlock: {
            /** Format: uuid */
            id: string;
            liturgy_id: string;
            name?: string;
            position?: number;
        };
        Bible: {
            /** Format: uuid */
            id: string;
            translation_id: string;
        };
        BibleBook: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            bible_id: string;
            canon_order: number;
            name_id?: string;
            name_lang: string;
            name_lang_abbr?: string;
        };
        BibleChapter: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            bible_book_id: string;
            number: number;
        };
        BibleTranslation: {
            id: string;
            abbr: string;
            name: string;
        };
        /** @description A collection of content items grouped together. */
        Pack: {
            /** Format: uuid */
            id: string;
            name: string;
            author?: string;
            description?: string;
            /** Format: date */
            created_at?: string;
        };
        PackItem: {
            /** Format: uuid */
            pack_id: string;
            /** Format: uuid */
            content_id: string;
        };
        Slide: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            content_id: string;
            position?: number;
        };
        SlideColumn: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            slide_id: string;
            content_type: components["schemas"]["ContentType"];
            position?: number;
            content?: string;
            header?: string;
        };
        Tag: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        TagAssignment: {
            /** Format: uuid */
            tag_id: string;
            /** Format: uuid */
            content_id: string;
            content_type: components["schemas"]["ContentType"];
        };
        Tables: {
            content?: components["schemas"]["Content"][];
            hymn?: components["schemas"]["Hymn"][];
            liturgy?: components["schemas"]["Liturgy"][];
            liturgy_block?: components["schemas"]["LiturgyBlock"][];
            bible?: components["schemas"]["Bible"][];
            bible_book?: components["schemas"]["BibleBook"][];
            bible_chapter?: components["schemas"]["BibleChapter"][];
            bible_translation?: components["schemas"]["BibleTranslation"][];
            pack?: components["schemas"]["Pack"][];
            pack_item?: components["schemas"]["PackItem"][];
            slide?: components["schemas"]["Slide"][];
            slide_column?: components["schemas"]["SlideColumn"][];
            tag?: components["schemas"]["Tag"][];
        };
        BibleView: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["ContentType"];
            created_at: string;
            translation: components["schemas"]["BibleTranslation"];
            books_count: number;
            chapters_count: number;
        };
        BibleBookView: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["ContentType"];
            created_at: string;
            canon_order: number;
            name_id: string;
            name_lang: string;
            name_lang_abbr?: string;
            bible: {
                /** Format: uuid */
                id?: string;
                translation?: components["schemas"]["BibleTranslation"];
            };
            chapters_count: number;
            chapters: {
                id?: string;
                number?: number;
            }[];
        };
        BibleChapterView: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["ContentType"];
            created_at: string;
            number: number;
            book: {
                /** Format: uuid */
                id?: string;
                name_id?: string;
                name_lang?: string;
                name_lang_abbr?: string;
            };
            bible: {
                /** Format: uuid */
                id?: string;
                translation?: components["schemas"]["BibleTranslation"];
            };
            slides: components["schemas"]["SlideView"][];
            display_name: string;
            short_display_name: string;
        };
        BibleBooksPagedView: {
            items: components["schemas"]["BibleBook"][];
            pagination: components["schemas"]["PaginationInfo"];
            bible_data: components["schemas"]["Bible"];
            translation_data: components["schemas"]["BibleTranslation"];
        };
        BibleChaptersPagedView: {
            items: components["schemas"]["BibleChapter"][];
            pagination: components["schemas"]["PaginationInfo"];
            book_data: components["schemas"]["BibleBook"];
            translation_data: components["schemas"]["BibleTranslation"];
        };
        ContentSlidesView: {
            /** Format: uuid */
            content_id?: string;
            content_type: components["schemas"]["ContentType"];
            slides: components["schemas"]["SlideView"][];
        };
        /** @description A database view for ease of use on frontend side */
        HymnView: {
            /** Format: uuid */
            id: string;
            name: string;
            author?: string;
            composer?: string;
            /** Format: date */
            created_at?: string;
            tags?: string[];
            slides?: components["schemas"]["SlideView"][];
        };
        /** @description A pack containing multiple items. */
        PackView: {
            /** Format: uuid */
            id?: string;
            name?: string;
            author?: string;
            description?: string;
            /** Format: date */
            created_at?: string;
            pagination?: components["schemas"]["PaginationInfo"];
            items?: components["schemas"]["PackItemView"][];
        };
        /** @enum {string} */
        ContentType: ContentType;
        /** @description A column in a slide */
        SlideColumnView: {
            id: string;
            position: number;
            header: string;
            content: string;
        };
        SlideView: {
            slide_id: string;
            position: number;
            columns?: components["schemas"]["SlideColumnView"][];
        };
        PaginationInfo: {
            current_page?: number;
            page_size?: number;
            total_items?: number;
            total_pages?: number;
            min_page?: number;
            max_page?: number;
            has_next?: boolean;
            has_previous?: boolean;
            next_page?: number;
            previous_page?: number;
            first_page?: number;
            last_page?: number;
            items_on_current_page?: number;
            offset?: number;
            is_first_page?: boolean;
            is_last_page?: boolean;
        };
        BlockView: {
            /** Format: uuid */
            block_id: string;
            name: string;
            position: number;
            slides?: components["schemas"]["SlideView"][];
        };
        /** @description A view to show liturgy and its blocks and slides */
        LiturgyView: {
            /** Format: uuid */
            liturgy_id: string;
            liturgy_name: string;
            blocks?: components["schemas"]["BlockView"][];
        };
        /** @description A pack item showing its type (hymn, bible, liturgy) and id only */
        PackItemView: {
            id: string;
            type: components["schemas"]["ContentType"];
            /** Format: date */
            create_at?: string;
            content?: components["schemas"]["HymnView"] | components["schemas"]["LiturgyView"] | components["schemas"]["BibleView"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export enum ContentType {
    hymn = "hymn",
    liturgy = "liturgy",
    liturgy_block = "liturgy_block",
    bible = "bible",
    bible_book = "bible_book",
    bible_chapter = "bible_chapter"
}
export type operations = Record<string, never>;
